package com.example.data

import kotlinx.coroutines.flow.Flow
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class InventoryRepository(
    private val taskDao: TaskDao,
    private val inventoryDao: InventoryDao
) {
    val allTasks: Flow<List<Task>> = taskDao.getAllTasksFlow()
    val allItems: Flow<List<InventoryItem>> = inventoryDao.getAllItemsFlow()

    // Activity log of rules executed during the session
    val ruleActivityLog = mutableListOf<String>()

    init {
        logRuleEvent("System Initialized", "Rule engine standby. Fully offline processing operational.")
    }

    private fun logRuleEvent(ruleName: String, action: String) {
        val timeStr = SimpleDateFormat("HH:mm:ss", Locale.getDefault()).format(Date())
        ruleActivityLog.add(0, "[$timeStr] Rule '$ruleName' -> $action")
        // Limit log size to 100 entries
        if (ruleActivityLog.size > 100) {
            ruleActivityLog.removeAt(ruleActivityLog.lastIndex)
        }
    }

    suspend fun getTaskById(id: Int): Task? = taskDao.getTaskById(id)
    suspend fun insertTask(task: Task): Long {
        return taskDao.insertTask(task)
    }
    suspend fun deleteTask(task: Task) = taskDao.deleteTask(task)
    suspend fun deleteTaskById(id: Int) = taskDao.deleteById(id)
    suspend fun updateTaskStatus(id: Int, status: String) {
        taskDao.updateTaskStatus(id, status)
        // Check if completing this task can trigger any rule sequence
        val task = taskDao.getTaskById(id)
        if (task != null) {
            logRuleEvent("Task Modified", "Task ID #${task.id} set to $status (${task.title})")
        }
    }

    suspend fun getItemById(id: Int): InventoryItem? = inventoryDao.getItemById(id)
    
    suspend fun insertItem(item: InventoryItem): Long {
        val id = inventoryDao.insertItem(item)
        // Run rules immediately on insert
        runRulesForItem(id.toInt())
        return id
    }

    suspend fun deleteItem(item: InventoryItem) {
        // Also delete / complete linked offline recommendations
        val linkedTasks = taskDao.getPendingTasksForItem(item.id)
        for (task in linkedTasks) {
            if (task.isAutoGenerated) {
                taskDao.deleteTask(task)
                logRuleEvent("Clean Orphans", "Removed orphaned auto-task '${task.title}' for deleted item '${item.name}'")
            }
        }
        inventoryDao.deleteItem(item)
    }

    suspend fun updateStock(id: Int, quantity: Int) {
        inventoryDao.updateStock(id, quantity)
        // Evaluate rules
        runRulesForItem(id)
    }

    /**
     * Offline Decision Engine Rules
     * Runs our deterministic, fully local expert rules to sync state.
     */
    suspend fun runRulesForAll() {
        val items = inventoryDao.getAllItemsSync()
        for (item in items) {
            evaluateRules(item)
        }
    }

    private suspend fun runRulesForItem(itemId: Int) {
        val item = inventoryDao.getItemById(itemId)
        if (item != null) {
            evaluateRules(item)
        }
    }

    private suspend fun evaluateRules(item: InventoryItem) {
        val now = System.currentTimeMillis()
        val pendingTasks = taskDao.getPendingTasksForItem(item.id)

        // RULE 1: Stock Level Heuristic
        if (item.quantity <= item.minThreshold) {
            val title = "Restock ${item.name}"
            val exists = pendingTasks.any { it.title == title }
            if (!exists) {
                // Generate Restock Task
                val isOut = item.quantity == 0
                val urgency = if (isOut) "CRITICAL" else "HIGH"
                val description = if (isOut) {
                    "CRITICAL STOCK ALERT: '${item.name}' is completely depleted! Restock immediately. (Level: 0, Threshold: ${item.minThreshold})"
                } else {
                    "Low inventory warning for '${item.name}': current status stands at ${item.quantity} units, dropping below safe margin of ${item.minThreshold}."
                }

                val autoTask = Task(
                    title = title,
                    description = description,
                    priority = urgency,
                    status = "PENDING",
                    category = "Inventory (Auto)",
                    linkedItemId = item.id,
                    isAutoGenerated = true
                )
                taskDao.insertTask(autoTask)
                logRuleEvent(
                    "Low Stock Heuristic",
                    "Auto-generated $urgency priority restock command for '${item.name}' (current density is ${item.quantity}/${item.minThreshold})."
                )
            }
        } else {
            // RULE 2: Replenishment Resolution Helper
            // Auto-complete previous low stock tasks if stock goes back up!
            val restockTaskPattern = "Restock ${item.name}"
            val uncompletedRestocks = pendingTasks.filter { it.title == restockTaskPattern }
            if (uncompletedRestocks.isNotEmpty()) {
                for (task in uncompletedRestocks) {
                    taskDao.updateTaskStatus(task.id, "COMPLETED")
                    logRuleEvent(
                        "Replenish Resolver",
                        "Satisifed and closed task '${task.title}' for '${item.name}'. Asset inventory restored to safe level: ${item.quantity} units."
                    )
                }
            }
        }

        // RULE 3: Expiry Date Heuristic
        item.expiryDate?.let { expiry ->
            val daysLeftMill = expiry - now
            val daysLeft = daysLeftMill / (1000 * 60 * 60 * 24)
            val title = "Check Expiry: ${item.name}"
            
            if (daysLeft in 0..3) {
                // Expiry warning task
                val exists = pendingTasks.any { it.title == title }
                if (!exists) {
                    val dateStr = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date(expiry))
                    val urgency = if (daysLeft <= 1) "CRITICAL" else "MEDIUM"
                    val autoTask = Task(
                        title = title,
                        description = "POTENTIAL SPOILAGE/EXPIRY WARNING: Sub-threshold item '${item.name}' is expiring in $daysLeft days ($dateStr). Ensure rotation or usage.",
                        priority = urgency,
                        status = "PENDING",
                        category = "Inventory (Auto)",
                        linkedItemId = item.id,
                        isAutoGenerated = true
                    )
                    taskDao.insertTask(autoTask)
                    logRuleEvent(
                        "Expiry Monitor",
                        "Secured critical action directive: '${item.name}' expires $dateStr. Priority assigned: $urgency."
                    )
                }
            } else if (daysLeft < 0) {
                // Already expired
                val expiredTitle = "EXPIRED: ${item.name}"
                val exists = pendingTasks.any { it.title == expiredTitle }
                if (!exists) {
                    val autoTask = Task(
                        title = expiredTitle,
                        description = "EXPIRED MATERIAL RESOURCE: '${item.name}' has exceeded its specified storage limit. Immediate disposal recommended.",
                        priority = "CRITICAL",
                        status = "PENDING",
                        category = "Inventory (Auto)",
                        linkedItemId = item.id,
                        isAutoGenerated = true
                    )
                    taskDao.insertTask(autoTask)
                    logRuleEvent(
                        "Spoilage Rule",
                        "Triggered immediate disposal directive for '${item.name}'. Resource was past date code."
                    )
                }
            }
        }
    }
}
