package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "tasks")
data class Task(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val priority: String, // "LOW", "MEDIUM", "HIGH", "CRITICAL"
    val status: String, // "PENDING", "COMPLETED"
    val dueDate: Long? = null,
    val category: String = "General",
    val linkedItemId: Int? = null, // Linked InventoryItem.id
    val isAutoGenerated: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)
